### ISSUE TITLE
Problem with installation on macOS Mojave.

### ISSUE THREAD

**Issue by yaroslav-zhumagulov** [HugoStrand/tprf#2]
Dear Hugo,

I'm trying install TPRF on macOS Mojave.

During the compilation, I got the following error:

Undefined symbols for architecture x86_64:
  "_omp_get_num_threads", referenced from:
      tprf::chiq_sum_nu_from_chi0q_and_gamma_PH(triqs::gfs::gf_view<triqs::gfs::cartesian_product<triqs::gfs::imfreq, triqs::gfs::imfreq, triqs::lattice::brillouin_zone>, triqs::gfs::tensor_valued<4> >, triqs::gfs::gf_view<triqs::gfs::cartesian_product<triqs::gfs::imfreq, triqs::gfs::imfreq, triqs::gfs::imfreq>, triqs::gfs::tensor_valued<4> >) in chi_imfreq.cpp.o
  "_omp_get_thread_num", referenced from:
      tprf::chiq_sum_nu_from_chi0q_and_gamma_PH(triqs::gfs::gf_view<triqs::gfs::cartesian_product<triqs::gfs::imfreq, triqs::gfs::imfreq, triqs::lattice::brillouin_zone>, triqs::gfs::tensor_valued<4> >, triqs::gfs::gf_view<triqs::gfs::cartesian_product<triqs::gfs::imfreq, triqs::gfs::imfreq, triqs::gfs::imfreq>, triqs::gfs::tensor_valued<4> >) in chi_imfreq.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [c++/libtprf_c.dylib] Error 1
make[1]: *** [c++/CMakeFiles/tprf_c.dir/all] Error 2
make: *** [all] Error 2

I would appreciate if you help me with this problem,

Yaroslav.

**Comment by HugoStrand** [comment]
Dear Yaroslav,

Thank you for reporting, and for being the third official user of `TPRF` 👍 

The symbols that are missing are part of the threading library OpenMP. If you add the compiler flag `-fopenmp` (for the gcc compiler suite) when compiling this should go away.

Please be aware that `tprf` has not been officially released yet, since it is still under heavy development. So you might run into issues with installation and usage. I am sorry.

Cheers, Hugo

**Comment by yaroslav-zhumagulov** [comment]
Resolved by putting in .bash_profile following line
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

**Comment by HugoStrand** [comment]
Dear Yaroslav,

Ok! Good. 

Instead of putting the flags "globally" in your `.bash_profile` you can pass these flags only to the linking stage of TPRF by passing CMAKE linker flags like:

```
cmake \
  -DCMAKE_LIBRARY_PATH="/usr/local/opt/llvm/lib"
  -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-rpath,/usr/local/opt/llvm/lib" \
  -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath,/usr/local/opt/llvm/lib" \
```
Cheers, Hugo
